version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "doubleguesser-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w7rw538tjir6"
s3_prefix = "doubleguesser-sam-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "ConnectionTableName=\"doubleguesser_connections\" GameTableName=\"doubleguesser_game_states\""
image_repositories = []
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true