AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Infrastructure for the game Double Guesser by Sergei Sidorov

Globals:
    Function:
        Timeout: 30
        Tags:
            project: doubleguesser

Parameters:
    ConnectionTableName:
        Type: String
        Default: 'doubleguesser_connections'
    GameTableName:
        Type: String
        Default: 'doubleguesser_game_states'

Resources:
    TablesTemplate:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Retain
        Properties:
            TemplateURL: SAM_templates/tables/template.yaml
            Tags:
                - Key: project
                  Value: doubleguesser
            Parameters:
                ConnectionTableName: !Ref ConnectionTableName
                GameTableName: !Ref GameTableName
    ApiLambdasTemplate:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Retain
        DependsOn:
            - TablesTemplate
        Properties:
            TemplateURL: SAM_templates/api-lambdas/template.yaml
            Tags:
                - Key: project
                  Value: doubleguesser
            Parameters:
                ConnectionTableName: !Ref ConnectionTableName
                GameTableName: !Ref GameTableName
    ApiTemplate:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Retain
        DependsOn:
            - ApiLambdasTemplate
        Properties:
            TemplateURL: SAM_templates/api/template.yaml
            Tags:
                - Key: project
                  Value: doubleguesser
            Parameters:
                CreateRoomArn: !GetAtt ApiLambdasTemplate.Outputs.CreateRoomArn
                JoinRoomArn: !GetAtt ApiLambdasTemplate.Outputs.JoinRoomArn
                LeaveRoomArn: !GetAtt ApiLambdasTemplate.Outputs.LeaveRoomArn
                RejoinRoomArn: !GetAtt ApiLambdasTemplate.Outputs.RejoinRoomArn
                UpdateGameArn: !GetAtt ApiLambdasTemplate.Outputs.UpdateGameArn

    PermissionTemplate:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Retain
        DependsOn:
            - ApiLambdasTemplate
        Properties:
            TemplateURL: SAM_templates/permission/template.yaml
            Tags:
                - Key: project
                  Value: doubleguesser
            Parameters:
                CreateRoomFunction: !GetAtt ApiLambdasTemplate.Outputs.CreateRoomFunction
                JoinRoomFunction: !GetAtt ApiLambdasTemplate.Outputs.JoinRoomFunction
                LeaveRoomFunction: !GetAtt ApiLambdasTemplate.Outputs.LeaveRoomFunction
                RejoinRoomFunction: !GetAtt ApiLambdasTemplate.Outputs.RejoinRoomFunction
                UpdateGameFunction: !GetAtt ApiLambdasTemplate.Outputs.UpdateGameFunction
    LambdasTemplate:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Retain
        DependsOn:
            - ApiTemplate
            - TablesTemplate
        Properties:
            TemplateURL: SAM_templates/lambdas/template.yaml
            Tags:
                - Key: project
                  Value: doubleguesser
            Parameters:
                ConnectionTableName: !Ref ConnectionTableName
                GameTableName: !Ref GameTableName
                GameTableStream: !GetAtt TablesTemplate.Outputs.GameTableStream
                DoubleGuesserWebSocket: !GetAtt ApiTemplate.Outputs.DoubleGuesserWebSocket
                Stage: !GetAtt ApiTemplate.Outputs.Stage
Outputs:
    WebSocketURI:
        Description: 'The WSS Protocol URI to connect to'
        Value:
            !Join [
                '',
                [
                    'wss://',
                    !GetAtt ApiTemplate.Outputs.DoubleGuesserWebSocket,
                    '.execute-api.',
                    !Ref 'AWS::Region',
                    '.amazonaws.com/',
                    !GetAtt ApiTemplate.Outputs.Stage,
                ],
            ]
