AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Lambda functions for doubleguesser api routes

Parameters:
    ConnectionTableName:
        Type: String
    GameTableName:
        Type: String

Resources:
    CreateRoomFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: CreateRoomLambda
            CodeUri: ../../lambdas/create-room/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    CONNECTIONS_TABLE_NAME: !Ref ConnectionTableName
                    GAMES_TABLE_NAME: !Ref GameTableName
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ConnectionTableName
                - DynamoDBCrudPolicy:
                      TableName: !Ref GameTableName
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /create-room
                        Method: post
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: false
                Target: 'es2020'
                Sourcemap: false
                External:
                    - aws-sdk
                    - aws-lambda
                EntryPoints:
                    - app.ts
    JoinRoomFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: JoinRoomLambda
            CodeUri: ../../lambdas/join-room/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    CONNECTIONS_TABLE_NAME: !Ref ConnectionTableName
                    GAMES_TABLE_NAME: !Ref GameTableName
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ConnectionTableName
                - DynamoDBCrudPolicy:
                      TableName: !Ref GameTableName
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /join-room
                        Method: post
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: false
                Target: 'es2020'
                Sourcemap: false
                External:
                    - aws-sdk
                    - aws-lambda
                EntryPoints:
                    - app.ts
    LeaveRoomFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: LeaveRoomLambda
            CodeUri: ../../lambdas/leave-room/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    CONNECTIONS_TABLE_NAME: !Ref ConnectionTableName
                    GAMES_TABLE_NAME: !Ref GameTableName
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ConnectionTableName
                - DynamoDBCrudPolicy:
                      TableName: !Ref GameTableName
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /leave-room
                        Method: post
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: false
                Target: 'es2020'
                Sourcemap: false
                External:
                    - aws-sdk
                    - aws-lambda
                EntryPoints:
                    - app.ts
    UpdateGameFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: UpdateGameLambda
            CodeUri: ../../lambdas/update-game/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    CONNECTIONS_TABLE_NAME: !Ref ConnectionTableName
                    GAMES_TABLE_NAME: !Ref GameTableName
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ConnectionTableName
                - DynamoDBCrudPolicy:
                      TableName: !Ref GameTableName
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /update-game
                        Method: post
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: false
                Target: 'es2020'
                Sourcemap: false
                External:
                    - aws-sdk
                    - aws-lambda
                EntryPoints:
                    - app.ts
    RejoinRoomFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: RejoinRoomLambda
            CodeUri: ../../lambdas/rejoin-room/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    CONNECTIONS_TABLE_NAME: !Ref ConnectionTableName
                    GAMES_TABLE_NAME: !Ref GameTableName
                    SEND_PLAYER_GAME_FUNCTION: SendPlayerGameFunction
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ConnectionTableName
                - DynamoDBCrudPolicy:
                      TableName: !Ref GameTableName
                - LambdaInvokePolicy:
                      FunctionName: SendPlayerGameFunction
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /rejoin
                        Method: post
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: false
                Target: 'es2020'
                Sourcemap: false
                External:
                    - aws-sdk
                    - aws-lambda
                EntryPoints:
                    - app.ts
    CreateRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref CreateRoomFunction
            Principal: apigateway.amazonaws.com
    JoinRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref JoinRoomFunction
            Principal: apigateway.amazonaws.com
    LeaveRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref LeaveRoomFunction
            Principal: apigateway.amazonaws.com
    RejoinRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref RejoinRoomFunction
            Principal: apigateway.amazonaws.com
    UpdateGamePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref UpdateGameFunction
            Principal: apigateway.amazonaws.com
Outputs:
    CreateRoomArn:
        Value: !GetAtt CreateRoomFunction.Arn
    JoinRoomArn:
        Value: !GetAtt JoinRoomFunction.Arn
    LeaveRoomArn:
        Value: !GetAtt LeaveRoomFunction.Arn
    RejoinRoomArn:
        Value: !GetAtt RejoinRoomFunction.Arn
    UpdateGameArn:
        Value: !GetAtt UpdateGameFunction.Arn
