AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Lambda permissions template for doubleguesser

Parameters:
    CreateRoomFunction:
        Type: String
    JoinRoomFunction:
        Type: String
    LeaveRoomFunction:
        Type: String
    RejoinRoomFunction:
        Type: String
    UpdateGameFunction:
        Type: String

Resources:
    CreateRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref CreateRoomFunction
            Principal: apigateway.amazonaws.com
    JoinRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref JoinRoomFunction
            Principal: apigateway.amazonaws.com
    LeaveRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref LeaveRoomFunction
            Principal: apigateway.amazonaws.com
    RejoinRoomPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref RejoinRoomFunction
            Principal: apigateway.amazonaws.com
    UpdateGamePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref UpdateGameFunction
            Principal: apigateway.amazonaws.com
